### ISSUE TITLE
Add Place information to datasets

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/sonar2021_demo#10]
Place information can be derived from songfacts.

**Comment by jonnybluesman** [comment]
This is already there, although it is not available for all tracks! As you can see from [this example](https://github.com/polifonia-project/sonar2021_demo/blob/datasets/datasets/songfacts/iso-queen/Bohemian_Rhapsody.json), when information about places is available, you should find: (i) the name of the place; and (ii) a list of facts on that place. In addition, in SongFacts, **places** and **images** are also very related. This is all documented in our list [here](https://liveunibo.sharepoint.com/:x:/r/sites/polifonia/Shared%20Documents/WP6/AI%26Music@Sonar2021/datasets/overview.xlsx?d=w352ea4d8aefe40cbb080d1c291c52998&csf=1&web=1&e=ZvM1Qs).

**Comment by enridaga** [comment]
I see, I guess what is missing is coordinate information, to display the place in a map. Maybe something that can be derived from [Geonames](http://www.geonames.org/)?

**Comment by enridaga** [comment]
Another way is using some NER and get the DBpedia/Wikidata entity to get the coordinates from. For example DBpedia Spotlight `https://www.dbpedia-spotlight.org/api` with your example "Aurora, Illinois":
```
curl -X GET "https://api.dbpedia-spotlight.org/en/annotate?text=Aurora%2C%20Illinois" -H "accept: application/json"

{
  "@text": "Aurora, Illinois",
  "@confidence": "0.5",
  "@support": "0",
  "@types": "",
  "@sparql": "",
  "@policy": "whitelist",
  "Resources": [
    {
      "@URI": "http://dbpedia.org/resource/Aurora,_Illinois",
      "@support": "1280",
      "@types": "Wikidata:Q515,Wikidata:Q486972,Schema:Place,Schema:City,DBpedia:Settlement,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:City",
      "@surfaceForm": "Aurora, Illinois",
      "@offset": "0",
      "@similarityScore": "0.9999999999997016",
      "@percentageOfSecondRank": "0.0"
    }
  ]
}
```
which will allow to get the coords from DBpedia `http://dbpedia.org/resource/Aurora,_Illinois`

**Comment by jonnybluesman** [comment]
Got it, then we will enrich all those annotations for which place information is available, ideally after a first step of aggregation to avoid spreading data all over. Thanks!

**Comment by jonnybluesman** [comment]
> Another way is using some NER and get the DBpedia/Wikidata entity to get the coordinates from. For example DBpedia Spotlight `https://www.dbpedia-spotlight.org/api` with your example "Aurora, Illinois":
> 
> ```
> curl -X GET "https://api.dbpedia-spotlight.org/en/annotate?text=Aurora%2C%20Illinois" -H "accept: application/json"
> 
> {
>   "@text": "Aurora, Illinois",
>   "@confidence": "0.5",
>   "@support": "0",
>   "@types": "",
>   "@sparql": "",
>   "@policy": "whitelist",
>   "Resources": [
>     {
>       "@URI": "http://dbpedia.org/resource/Aurora,_Illinois",
>       "@support": "1280",
>       "@types": "Wikidata:Q515,Wikidata:Q486972,Schema:Place,Schema:City,DBpedia:Settlement,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:City",
>       "@surfaceForm": "Aurora, Illinois",
>       "@offset": "0",
>       "@similarityScore": "0.9999999999997016",
>       "@percentageOfSecondRank": "0.0"
>     }
>   ]
> }
> ```
> 
> which will allow to get the coords from DBpedia `http://dbpedia.org/resource/Aurora,_Illinois`

Looks promising, thanks for the suggestion!
