### ISSUE TITLE
UI initial prototype with Youtube player

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/sonar2021_demo#11]
UI embedding a youtube player, keeping only basic controls (play, stop, forward, backword, scroll)

**Comment by enridaga** [comment]
This could be setup in a new UI branch or reuse any of the existing prototypes

**Comment by ccolonna** [comment]
Hi @JaseMK , I was taught to have a ```develop``` and a ```master``` branch.  ```master``` collects production code. ```develop``` collects development code, to be examined by other people, for UAT (user acceptance test) and eventually delivered in production. Generally I create a new branch from ```develop``` when a new feature is to implemented (for example ```ui-youtube-player``` or ```angular-project-setup```). When the new branch is completed than is merged into ```develop```. People can then examine the new feature from in development code, and if they approved it for production, ```develop``` is than merged into ```master```.
Eventually CI/CD can be configured both for ```develop``` and ```master``` to always have production and development code online, at which other people can look at. (E.g. configured to send code online everytime you have a new commit on these branches).

I report this just to tell as I moved until now. You can freely merge everything you produce on top of ```develop``` branch. For example the angular basic skeleton.

In any case as I guess you are much more experienced than me, if you have another development process/flow in mind just express that and I can happily align to that :)
As we haven't discussed about these until now I simply begun with what I was used to.

**Comment by delfimpandiani** [comment]
Hello, here are some updated sketches with the Youtube player incorporated into them:

<img width="1440" alt="Screen Shot 2021-09-14 at 12 13 32 PM" src="https://user-images.githubusercontent.com/44606644/133273041-465588aa-631c-4a50-9de0-c12c16450d8a.png">

Of course, even though in the sketches the youtube player shows the same image (as if it was always in the same second of the song) each of the sketches should actually show a different image/part of the video, as they go through time and thus would be at different seconds of the song. I thought it wasn't worth the time to do that at this point, but anyone thinks it is important I can do that edit soon.

@ccolonna you should probably use these to guide the html templates you are working on?

Hope this is helpful!

**Comment by JaseMK** [comment]
YouTube interface prototype complete
