### ISSUE TITLE
Lyrics similarity

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/sonar2021_demo#13]
To document activity on generating links between songs analysing the lyrics.

**Comment by roccotrip** [comment]
Suggestions on the csv format
- add an ID for each lyrics
- add a language field for each lyrics

**Comment by enridaga** [comment]
Added ID and Lang.

 - ID is a deterministic, numeric hash, not a sequential identifier. Cannot generate a serial ID with SPARQL Anything yet, see https://github.com/SPARQL-Anything/sparql.anything/issues/86

**Comment by enridaga** [comment]
OK, CSVs includes now all the lyrics from `genius` and `songfacts`, with ID and language. 

See queries/README.md for instructions on how to reproduce.

**Comment by roccotrip** [comment]
Probably we will have to remove duplicates, i.e., two versions of the same song. At the moment, I am removing them post hoc when I compute lyrics similarity but I think it would be better to decide how to handle these cases.
