### ISSUE TITLE
UI: import app data from toy json file to real jsonld file.

### ISSUE THREAD

**Issue by ccolonna** [polifonia-project/sonar2021_demo#28]
Waiting for https://github.com/polifonia-project/sonar2021_demo/issues/27 to be completed. Temporary fastest solution.

**Comment by ccolonna** [comment]
Changing in `song.service.ts`:
```js
// import ApplicationData from '../assets/data/data_v1.json';
import ApplicationData from '../assets/data/data_v3.json';
```
Changing in `video.component.ts`:
```js
    this.queueService.addToQueueByID('https://w3id.org/polifonia/resource/Recording/00001');
    this.queueService.addToQueueByID('https://w3id.org/polifonia/resource/Recording/00002');
    this.queueService.addToQueueByID('https://w3id.org/polifonia/resource/Recording/00003');
    this.queueService.addToQueueByID('https://w3id.org/polifonia/resource/Recording/00004');
    // this.queueService.addToQueueByID('1001');
    // this.queueService.addToQueueByID('1002');
    // this.queueService.addToQueueByID('1003');
    // this.queueService.addToQueueByID('1004');
```

The video player correctly show new songs.
In [data_v3](https://github.com/polifonia-project/sonar2021_demo/blob/develop/src/assets/data/data_v3.json) all items have the same youtubeID. So it resolve always playing penny lane.

There is a problem yet, annotations are not shown. 

This is an example annotation in the file `data_v1`:
```
    {
      "id": "https://w3id.org/polifonia/resource/SpatialAnnotation/00001_edited_at",
      "type": "spatial",
      "description": "This track was edited at Abbey Road Studios: Studio 1",
      "songID": "https://w3id.org/polifonia/resource/Recording/00001",
      "timestamp": 15,
      "metadata": {
        "long": "-0.17835",
        "lat": "51.53192",
        "placeName": "Abbey Road Studios: Studio 1"
      },
      "relationships": [
        {
          "songID": "https://w3id.org/polifonia/resource/Recording/1002",
          "type": "spatial",
          "score": 0.910762874582187
        }
      ]
    }
```

An example in `data_v1`:

```
      "id": "2001",
      "songID": "1001",
      "timestamp": 5,
      "type": "lyrics",
      "relationships": [
        {
          "songID": "1002",
          "type": "lyrics",
          "score": 45
        }
      ],
      "description": "These lyrics refer to a barbershop in Liverpool"
    },
```

**Comment by JaseMK** [comment]
The annotation service was still importing its application data from the v1 file. I have just pushed an update to this branch to fix that. Some annotations appear now, although there are some other bugs related to how and when they appear. I'm happy to investigate these issues this afternoon.

We should probably have a single config file that references the application data location and all other services and modules simply reference the config file.

**Comment by ccolonna** [comment]
Another problem:
```
The song IDs in the related songs (in annotations) don’t exist in the songs DB. Songs are ‘00001’, ‘00002’ etc and related songs are ‘10001’, ‘10002’ etc. 
```

We will take care of this when working on 
- https://github.com/polifonia-project/sonar2021_demo/issues/37
- https://github.com/polifonia-project/sonar2021_demo/issues/36
