### ISSUE TITLE
SONAR: Dataset investigation

### ISSUE THREAD

**Issue by FiorelaCiroku** [polifonia-project/sonar2021_demo#4]
## Task description

This task consists of Identifying candidate sources (audio, text, structures data) that can be combined to the sonar experiment. Validation of relevance and suitability of datasets must be done with an expert: Angelo Pompilo may be our reference expert, but others are more than welcome.

## Progress 
> To be completed

**Comment by enridaga** [comment]
Youtube link to be added to the Genius dataset
