### ISSUE TITLE
Apply annotation type styles to filters page

### ISSUE THREAD

**Issue by JaseMK** [polifonia-project/sonar2021_demo#46]
@ccolonna , are you able to apply your coloured annotation styles and icons to the filter toggles on the filters page? I'm not sure exactly how you've implemented these elsewhere so it might be easier for you. Once this is done, the 'feature/filter-page' branch can be merged back onto 'develop'

**Comment by ccolonna** [comment]
Yes @JaseMK . I will fix it as soon as I can.

**Comment by ccolonna** [comment]
Done in https://github.com/polifonia-project/sonar2021_demo/commit/cc7695d378b14842a8059f5cb738515bc1287fe4 .
